name: OCI ARM Capacity Hunter

on:
  workflow_dispatch: # Cho phép bấm nút chạy thủ công
  schedule:
    - cron: '*/15 * * * *' # Tự động chạy mỗi 15 phút (nên để từ 5-20 phút để tránh bị khóa tài khoản)

jobs:
  hunt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3']
    name: Hunting Instance (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2 # Giữ ở v2 theo độ ổn định của cộng đồng
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4 # Cập nhật lên v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run script to create instance
        run: php index.php # Đổi từ phpunit sang chạy index.php để thực hiện tạo VPS
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ${{ secrets.OCI_PRIVATE_KEY_FILENAME }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_SHAPE: ${{ secrets.OCI_SHAPE }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
